FROM nvcr.io/nvidia/isaac-sim:2023.1.0-hotfix.1
COPY ./ /workspace/omniisaacgymenvs/
RUN /isaac-sim/python.sh -m pip install --upgrade pip && \
     /isaac-sim/python.sh -m pip install -e /workspace/omniisaacgymenvs
RUN echo 'alias PYTHON_PATH=/isaac-sim/python.sh' >> /etc/bash.bashrc
ENTRYPOINT ["sh", "-c", "cd /workspace/omniisaacgymenvs/omniisaacgymenvs && bash"]
