params:
  seed: ${...seed}
  algo:
    name: a2c_continuous

  model:
    name: continuous_a2c_logstd

  network:
    name: actor_critic
    separate: False

    space:
      continuous:
        mu_activation: None
        sigma_activation: None
        mu_init:
          name: default
        sigma_init:
          name: const_initializer
          val: 0
        fixed_sigma: True
    mlp:
      units: [256,512,256,128] #[256, 128, 64]
      activation: elu
      d2rl: False

      initializer:
        name: default
      regularizer:
        name: None

  load_checkpoint: ${if:${...checkpoint},True,False}
  load_path: ${...checkpoint}

  config:
    name: ${resolve_default:FactoryCube,${....experiment}}
    full_experiment_name: ${.name}
    device: ${....rl_device}
    device_name: ${....rl_device}
    env_name: rlgpu
    multi_gpu: False
    ppo: True
    mixed_precision: True
    normalize_input: True
    normalize_value: True
    value_bootstrap: True
    num_actors: ${....task.env.numEnvs}
    reward_shaper:
      scale_value: 1.0
    normalize_advantage: True
    gamma: 0.996
    tau: 0.95
    learning_rate: 2e-4 #5e-5 #1e-4
    lr_schedule: adaptive
    # schedule_type: standard
    kl_threshold: 0.004 # 0.008     # target kl for adaptive lr
    score_to_win: 200000000
    max_epochs: ${resolve_default:500,${....max_iterations}}
    save_best_after: 50
    save_frequency: 50
    print_stats: True
    grad_norm: 1.0
    entropy_coef: 0.0008
    truncate_grads: False
    e_clip: 0.2
    horizon_length: 1600 #3200
    minibatch_size: 32000 #64000
    mini_epochs: 8
    critic_coef: 2
    clip_value: True
    seq_len: 4
    bounds_loss_coef: 0.0003 #1
