params:
  seed: ${...seed}
  algo:
    name: sac

  model:
    name: soft_actor_critic

  network:
    name: soft_actor_critic
    separate: True

    space:
      continuous:
    mlp:
      units: [512, 256]
      activation: relu
      
      initializer:
        name: default
    log_std_bounds: [-5, 2]

  load_checkpoint: ${if:${...checkpoint},True,False}
  load_path: ${...checkpoint}

  config:
    name: ${resolve_default:CubeTaskSAC,${....experiment}}
    full_experiment_name: ${.name}
    device: ${....rl_device}
    device_name: ${....rl_device}
    env_name: rlgpu
    multi_gpu: False
    normalize_input: True
    num_actors: ${....task.env.numEnvs}
    reward_shaper:
      scale_value: 1.0
    max_epochs: ${resolve_default:4000,${....max_iterations}}
    save_best_after: 50
    save_frequency: 50
    print_stats: True
    gamma: 0.996
    init_alpha: 0.1
    alpha_lr: 0.0005 #0.005
    actor_lr: 0.0005
    critic_lr: 0.0005
    critic_tau: 0.005
    batch_size: 8192
    learnable_temperature: true
    num_seed_steps: 5
    num_warmup_steps: 800 #10
    num_steps_per_episode:  800 #8
    replay_buffer_size: 1000000