params:
  seed: ${...seed}
  algo:
    name: a2c_continuous

  model:
    name: continuous_a2c_logstd

  network:
    name: actor_critic
    separate: False

    space:
      continuous:
        mu_activation: None
        sigma_activation: None
        mu_init:
          name: default
        sigma_init:
          name: const_initializer
          val: 0
        fixed_sigma: True
    mlp:
      units: [256,512,256,128] #[256, 128, 64]
      activation: elu
      d2rl: False

      initializer:
        name: default
      regularizer:
        name: None

  load_checkpoint: ${if:${...checkpoint},True,False}
  load_path: ${...checkpoint}

  config:
    name: ${resolve_default:SoftclawCubeTask,${....experiment}}
    full_experiment_name: ${.name}
    device: ${....rl_device}
    device_name: ${....rl_device}
    env_name: rlgpu
    multi_gpu: False
    ppo: True
    mixed_precision: True
    normalize_input: True
    normalize_value: True
    value_bootstrap: True
    num_actors: ${....task.env.numEnvs}
    reward_shaper:
      scale_value: 1.0
    normalize_advantage: true
    gamma: 0.999
    tau: 0.95
    learning_rate: 0.0001
    lr_schedule: adaptive
    kl_threshold: 0.01
    score_to_win: 200000000
    max_epochs: ${resolve_default:500,${....max_iterations}}
    save_best_after: 50
    save_frequency: 50
    print_stats: true
    grad_norm: 0.5
    entropy_coef: 0.0015
    truncate_grads: false
    e_clip: 0.2
    horizon_length: 2000
    minibatch_size: 4000
    mini_epochs: 8
    critic_coef: 2
    clip_value: true
    seq_len: 4
    bounds_loss_coef: 0.0003

